#!/usr/bin/env python

import sys, os
sys.path.append('/opt/bricklayer')
sys.path.append('/opt/bricklayer/utils')

if os.path.isdir('/opt/bricklayer'):
    os.chdir('/opt/bricklayer')

import main

if __name__ == '__main__':
    main.main_function()
